# Generated by Django 3.1.7 on 2021-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
