# Generated by Django 3.1.7 on 2021-05-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20210510_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
